import type { ScholarshipApplication } from "@/lib/types";

export const dummyApplications: ScholarshipApplication[] = [
  {
    id: "a1b2c3d4-0001-4000-a000-000000000001",
    applicant_name: "陳怡君",
    student_id: "112035001",
    department: "教育心理與諮商學系",
    advisor_name: "林明德",
    gpa: 4.12,
    gpa_scale: 4.3,
    submission_status: "submitted",
    review_status: "自動審核完成",
    submitted_at: "2026-04-20T10:30:00Z",
    created_at: "2026-04-18T08:00:00Z",
    files: [
      { field: "document_transcript", label: null, name: "成績單.pdf", path: "a1b2c3d4-0001/transcript.pdf", type: "application/pdf", size: 204800 },
      { field: "document_advisorRecommendation", label: null, name: "推薦函.pdf", path: "a1b2c3d4-0001/recommendation.pdf", type: "application/pdf", size: 153600 },
      { field: "document_learningPlan", label: null, name: "學習計畫.pdf", path: "a1b2c3d4-0001/plan.pdf", type: "application/pdf", size: 307200 },
      { field: "document_noFullTimeDeclaration", label: null, name: "切結書.pdf", path: "a1b2c3d4-0001/declaration.pdf", type: "application/pdf", size: 102400 },
    ],
    payload: {
      applicantInfo: {
        applicantName: "陳怡君",
        studentId: "112035001",
        department: "教育心理與諮商學系",
        email: "yijun.chen@gs.ncku.edu.tw",
        phone: "0912-345-678",
        advisorName: "林明德",
        admissionAcademicYear: "112",
        studyStatus: "新領",
        applicationType: "培育優秀博士生獎學金",
      },
      eligibility: {
        bachelorRankPercent: "10",
        masterGpa: "4.05",
        gpaScale: "4.3",
        masterPercentScore: "92",
        hasSpecialRecommendation: false,
        noFullTimeJob: true,
        notReceivingOtherScholarship: true,
        eligibilityNotes: "",
      },
      academicPerformance: {
        cumulativeGpa: "4.12",
        cumulativeGpaScale: "4.3",
        classRankPercent: "5",
        completedCredits: "24",
        conductScore: "95",
        transcriptNotes: "",
      },
      journals: [
        {
          doi: "10.1037/edu0000801",
          date: "2025-03-15",
          author: "Chen, Y.-C., Lin, M.-D., & Wang, H.-L.",
          applicantAuthorName: "Chen, Y.-C.",
          doiAuthorNames: ["Chen, Y.-C.", "Lin, M.-D.", "Wang, H.-L."],
          issns: ["0022-0663", "1939-2176"],
          title: "Metacognitive Strategies and Academic Achievement in East Asian Higher Education",
          journal: "Journal of Educational Psychology, 117(2), 234-251",
          reviewUnit: "APA",
          journalLevel: "I級期刊",
          indexSource: "依期刊索引對照表自動判別",
          isCorrespondingAuthor: false,
          hasTrustedDatabase: "是",
          database: "SSCI",
          authorOrder: "第一作者",
          authorOrderOriginal: "第一作者",
          authorOrderModified: false,
          authorOrderChangeNote: "",
          attachmentNote: "",
        },
        {
          doi: "10.1016/j.learninstruc.2025.101922",
          date: "2025-09-01",
          author: "Lin, M.-D., Chen, Y.-C., & Hsu, T.-F.",
          applicantAuthorName: "Chen, Y.-C.",
          doiAuthorNames: ["Lin, M.-D.", "Chen, Y.-C.", "Hsu, T.-F."],
          issns: ["0959-4752"],
          title: "Self-regulated learning interventions in Taiwanese graduate programs",
          journal: "Learning and Instruction, 89, 101922",
          reviewUnit: "Elsevier",
          journalLevel: "I級期刊",
          indexSource: "依期刊索引對照表自動判別",
          isCorrespondingAuthor: false,
          hasTrustedDatabase: "是",
          database: "SSCI",
          authorOrder: "第二作者",
          authorOrderOriginal: "第二作者",
          authorOrderModified: false,
          authorOrderChangeNote: "",
          attachmentNote: "",
        },
      ],
      conferences: [
        {
          date: "2025-07-10",
          author: "Chen, Y.-C. & Lin, M.-D.",
          title: "Exploring the Role of Growth Mindset in Doctoral Students' Persistence",
          conference: "2025 Annual Meeting of the American Educational Research Association (AERA)",
          organizer: "AERA",
          type: "口頭發表",
          database: "WOS proceedings",
          authorOrder: "第一作者",
        },
      ],
      researchExperiences: [
        {
          institution: "國科會計畫（林明德主持）",
          role: "研究助理",
          nature: "個別型計畫",
          duration: "2024/08 - 2025/07",
        },
      ],
      researchAwards: [
        {
          name: "竹師教育學院博士生研究獎助",
          projectNumber: "EDU-2025-003",
          amountOrItem: "NT$60,000",
          contribution: "獨立研究",
        },
      ],
      plannedResearch: [
        {
          title: "博士生學術韌性與自我調節學習之縱貫研究",
          expectedDate: "2027-06",
          targetVenue: "Contemporary Educational Psychology",
          hasTrustedDatabase: "是",
          database: "SSCI",
          advisor: "林明德",
        },
      ],
      otherAchievements: "2024年教育心理學國際研討會最佳論文獎",
      otherReviewDocuments: [{ name: "最佳論文獎證明" }],
    },
  },
  {
    id: "a1b2c3d4-0002-4000-a000-000000000002",
    applicant_name: "王建宏",
    student_id: "111035012",
    department: "特殊教育學系",
    advisor_name: "張雅芳",
    gpa: 3.89,
    gpa_scale: 4.3,
    submission_status: "submitted",
    review_status: "等待人工審核",
    submitted_at: "2026-04-19T14:20:00Z",
    created_at: "2026-04-15T09:00:00Z",
    files: [
      { field: "document_transcript", label: null, name: "成績單.pdf", path: "a1b2c3d4-0002/transcript.pdf", type: "application/pdf", size: 198000 },
      { field: "document_advisorRecommendation", label: null, name: "推薦函.pdf", path: "a1b2c3d4-0002/recommendation.pdf", type: "application/pdf", size: 140000 },
      { field: "document_learningPlan", label: null, name: "學習計畫.pdf", path: "a1b2c3d4-0002/plan.pdf", type: "application/pdf", size: 280000 },
      { field: "document_noFullTimeDeclaration", label: null, name: "切結書.pdf", path: "a1b2c3d4-0002/declaration.pdf", type: "application/pdf", size: 95000 },
    ],
    payload: {
      applicantInfo: {
        applicantName: "王建宏",
        studentId: "111035012",
        department: "特殊教育學系",
        email: "jianhong.wang@gs.ncku.edu.tw",
        phone: "0923-456-789",
        advisorName: "張雅芳",
        admissionAcademicYear: "111",
        studyStatus: "續領",
        applicationType: "培育優秀博士生獎學金",
      },
      eligibility: {
        bachelorRankPercent: "15",
        masterGpa: "3.85",
        gpaScale: "4.3",
        masterPercentScore: "88",
        hasSpecialRecommendation: false,
        noFullTimeJob: true,
        notReceivingOtherScholarship: true,
        eligibilityNotes: "",
      },
      academicPerformance: {
        cumulativeGpa: "3.89",
        cumulativeGpaScale: "4.3",
        classRankPercent: "12",
        completedCredits: "36",
        conductScore: "92",
        transcriptNotes: "",
      },
      journals: [
        {
          doi: "10.1177/07419325241234567",
          date: "2025-06-01",
          author: "Wang, J.-H. & Chang, Y.-F.",
          applicantAuthorName: "Wang, J.-H.",
          doiAuthorNames: ["Wang, J.-H.", "Chang, Y.-F."],
          issns: ["0741-9325"],
          title: "Inclusive Education Practices for Students with ASD in Taiwan",
          journal: "Remedial and Special Education, 46(3), 178-195",
          reviewUnit: "SAGE",
          journalLevel: "I級期刊",
          indexSource: "依期刊索引對照表自動判別",
          isCorrespondingAuthor: false,
          hasTrustedDatabase: "是",
          database: "SSCI",
          authorOrder: "第一作者",
          authorOrderOriginal: "第一作者",
          authorOrderModified: false,
          authorOrderChangeNote: "",
          attachmentNote: "",
        },
      ],
      conferences: [
        {
          date: "2025-11-20",
          author: "Wang, J.-H., Chang, Y.-F., & Lee, S.-W.",
          title: "Universal Design for Learning in East Asian Classrooms",
          conference: "Council for Exceptional Children (CEC) 2025 Convention",
          organizer: "CEC",
          type: "壁報發表",
          database: "SCOPUS proceedings",
          authorOrder: "第一作者",
        },
        {
          date: "2026-01-15",
          author: "Chang, Y.-F. & Wang, J.-H.",
          title: "Assistive Technology Integration: A Multi-Site Study",
          conference: "ATIA 2026 Conference",
          organizer: "ATIA",
          type: "口頭發表",
          database: "",
          authorOrder: "第二作者",
        },
      ],
      researchExperiences: [
        {
          institution: "教育部特教計畫（張雅芳主持）",
          role: "兼任研究助理",
          nature: "整合型計畫",
          duration: "2023/08 - 2025/07",
        },
      ],
      researchAwards: [],
      plannedResearch: [
        {
          title: "自閉症學生社交技巧介入方案成效之後設分析",
          expectedDate: "2027-03",
          targetVenue: "Journal of Autism and Developmental Disorders",
          hasTrustedDatabase: "是",
          database: "SSCI",
          advisor: "張雅芳",
        },
      ],
      otherAchievements: "",
      otherReviewDocuments: [],
    },
  },
  {
    id: "a1b2c3d4-0003-4000-a000-000000000003",
    applicant_name: "李佳穎",
    student_id: "113035003",
    department: "課程與教學學系",
    advisor_name: "黃志偉",
    gpa: 4.21,
    gpa_scale: 4.3,
    submission_status: "submitted",
    review_status: "人工審核完成",
    submitted_at: "2026-04-21T09:45:00Z",
    created_at: "2026-04-19T11:00:00Z",
    files: [
      { field: "document_transcript", label: null, name: "成績單.pdf", path: "a1b2c3d4-0003/transcript.pdf", type: "application/pdf", size: 210000 },
      { field: "document_advisorRecommendation", label: null, name: "推薦函.pdf", path: "a1b2c3d4-0003/recommendation.pdf", type: "application/pdf", size: 160000 },
      { field: "document_learningPlan", label: null, name: "學習計畫.pdf", path: "a1b2c3d4-0003/plan.pdf", type: "application/pdf", size: 290000 },
      { field: "document_noFullTimeDeclaration", label: null, name: "切結書.pdf", path: "a1b2c3d4-0003/declaration.pdf", type: "application/pdf", size: 100000 },
    ],
    payload: {
      applicantInfo: {
        applicantName: "李佳穎",
        studentId: "113035003",
        department: "課程與教學學系",
        email: "jiaying.li@gs.ncku.edu.tw",
        phone: "0934-567-890",
        advisorName: "黃志偉",
        admissionAcademicYear: "113",
        studyStatus: "新領",
        applicationType: "培育優秀博士生獎學金",
      },
      eligibility: {
        bachelorRankPercent: "5",
        masterGpa: "4.18",
        gpaScale: "4.3",
        masterPercentScore: "95",
        hasSpecialRecommendation: true,
        noFullTimeJob: true,
        notReceivingOtherScholarship: true,
        eligibilityNotes: "經系所特殊推薦",
      },
      academicPerformance: {
        cumulativeGpa: "4.21",
        cumulativeGpaScale: "4.3",
        classRankPercent: "3",
        completedCredits: "18",
        conductScore: "97",
        transcriptNotes: "",
      },
      journals: [
        {
          doi: "10.1080/03057267.2025.2301234",
          date: "2025-05-20",
          author: "Li, J.-Y., Huang, C.-W., & Tsai, M.-R.",
          applicantAuthorName: "Li, J.-Y.",
          doiAuthorNames: ["Li, J.-Y.", "Huang, C.-W.", "Tsai, M.-R."],
          issns: ["0305-7267", "1940-8412"],
          title: "STEM Curriculum Reform in Secondary Schools: A Taiwanese Perspective",
          journal: "Studies in Science Education, 61(1), 45-72",
          reviewUnit: "Taylor & Francis",
          journalLevel: "I級期刊",
          indexSource: "依期刊索引對照表自動判別",
          isCorrespondingAuthor: false,
          hasTrustedDatabase: "是",
          database: "SSCI",
          authorOrder: "第一作者",
          authorOrderOriginal: "第一作者",
          authorOrderModified: false,
          authorOrderChangeNote: "",
          attachmentNote: "",
        },
        {
          doi: "10.6151/CERQ.202503_22(1).0003",
          date: "2025-03-01",
          author: "李佳穎、黃志偉",
          applicantAuthorName: "李佳穎",
          doiAuthorNames: ["李佳穎", "黃志偉"],
          issns: ["1811-8909"],
          title: "十二年國教課綱實施後國中科技教育課程轉化之個案研究",
          journal: "當代教育研究季刊, 22(1), 67-98",
          reviewUnit: "國立臺灣師範大學教育研究與評鑑中心",
          journalLevel: "非I級期刊",
          indexSource: "依期刊索引對照表自動判別",
          isCorrespondingAuthor: false,
          hasTrustedDatabase: "是",
          database: "TSSCI",
          authorOrder: "第一作者",
          authorOrderOriginal: "第一作者",
          authorOrderModified: false,
          authorOrderChangeNote: "",
          attachmentNote: "",
        },
        {
          doi: "10.1002/tea.21890",
          date: "2026-01-10",
          author: "Huang, C.-W., Li, J.-Y., & Chen, P.-S.",
          applicantAuthorName: "Li, J.-Y.",
          doiAuthorNames: ["Huang, C.-W.", "Li, J.-Y.", "Chen, P.-S."],
          issns: ["0022-4308", "1098-2736"],
          title: "Inquiry-Based Teaching Efficacy: A Longitudinal Study in Taiwan",
          journal: "Journal of Research in Science Teaching, 63(2), 301-328",
          reviewUnit: "Wiley",
          journalLevel: "I級期刊",
          indexSource: "依期刊索引對照表自動判別",
          isCorrespondingAuthor: false,
          hasTrustedDatabase: "是",
          database: "SSCI",
          authorOrder: "第二作者",
          authorOrderOriginal: "第二作者",
          authorOrderModified: false,
          authorOrderChangeNote: "",
          attachmentNote: "",
        },
      ],
      conferences: [
        {
          date: "2025-08-25",
          author: "Li, J.-Y. & Huang, C.-W.",
          title: "Integrating Computational Thinking into Science Curriculum",
          conference: "European Science Education Research Association (ESERA) 2025",
          organizer: "ESERA",
          type: "口頭發表",
          database: "SCOPUS proceedings",
          authorOrder: "第一作者",
        },
      ],
      researchExperiences: [
        {
          institution: "國科會計畫（黃志偉主持）",
          role: "研究助理",
          nature: "個別型計畫",
          duration: "2024/02 - 2025/01",
        },
        {
          institution: "教育部教學實踐計畫（黃志偉主持）",
          role: "共同研究者",
          nature: "教學實踐研究計畫",
          duration: "2025/02 - 2026/01",
        },
      ],
      researchAwards: [
        {
          name: "國科會大專學生研究計畫（碩士班）",
          projectNumber: "MOST 113-2813-C-007-001-H",
          amountOrItem: "NT$48,000",
          contribution: "計畫主持人",
        },
      ],
      plannedResearch: [
        {
          title: "AI融入探究式教學模式之設計與評估",
          expectedDate: "2027-09",
          targetVenue: "Computers & Education",
          hasTrustedDatabase: "是",
          database: "SSCI",
          advisor: "黃志偉",
        },
      ],
      otherAchievements: "碩士論文獲中華民國課程與教學學會年度優秀論文獎",
      otherReviewDocuments: [{ name: "優秀論文獎證書" }, { name: "國科會計畫核定書" }],
    },
  },
  {
    id: "a1b2c3d4-0004-4000-a000-000000000004",
    applicant_name: "張宇軒",
    student_id: "112035008",
    department: "學習科學與科技學系",
    advisor_name: "吳美玲",
    gpa: 3.95,
    gpa_scale: 4.3,
    submission_status: "submitted",
    review_status: "資料錯誤",
    submitted_at: "2026-04-22T16:00:00Z",
    created_at: "2026-04-20T10:00:00Z",
    files: [
      { field: "document_transcript", label: null, name: "成績單.pdf", path: "a1b2c3d4-0004/transcript.pdf", type: "application/pdf", size: 195000 },
      { field: "document_advisorRecommendation", label: null, name: "推薦函.pdf", path: "a1b2c3d4-0004/recommendation.pdf", type: "application/pdf", size: 148000 },
      { field: "document_learningPlan", label: null, name: "學習計畫.pdf", path: "a1b2c3d4-0004/plan.pdf", type: "application/pdf", size: 310000 },
      { field: "document_noFullTimeDeclaration", label: null, name: "切結書.pdf", path: "a1b2c3d4-0004/declaration.pdf", type: "application/pdf", size: 98000 },
    ],
    payload: {
      applicantInfo: {
        applicantName: "張宇軒",
        studentId: "112035008",
        department: "學習科學與科技學系",
        email: "yuxuan.zhang@gs.ncku.edu.tw",
        phone: "0945-678-901",
        advisorName: "吳美玲",
        admissionAcademicYear: "112",
        studyStatus: "新領",
        applicationType: "培育優秀博士生獎學金",
      },
      eligibility: {
        bachelorRankPercent: "8",
        masterGpa: "3.90",
        gpaScale: "4.3",
        masterPercentScore: "90",
        hasSpecialRecommendation: false,
        noFullTimeJob: true,
        notReceivingOtherScholarship: true,
        eligibilityNotes: "",
      },
      academicPerformance: {
        cumulativeGpa: "3.95",
        cumulativeGpaScale: "4.3",
        classRankPercent: "8",
        completedCredits: "28",
        conductScore: "93",
        transcriptNotes: "",
      },
      journals: [
        {
          doi: "10.1007/s11423-025-10345-7",
          date: "2025-04-12",
          author: "Zhang, Y.-X. & Wu, M.-L.",
          applicantAuthorName: "Zhang, Y.-X.",
          doiAuthorNames: ["Zhang, Y.-X.", "Wu, M.-L."],
          issns: ["1042-1629", "1556-6501"],
          title: "Adaptive Learning Systems and Student Engagement: A Mixed-Methods Study",
          journal: "Educational Technology Research and Development, 73(2), 412-438",
          reviewUnit: "Springer",
          journalLevel: "I級期刊",
          indexSource: "依期刊索引對照表自動判別",
          isCorrespondingAuthor: false,
          hasTrustedDatabase: "是",
          database: "SSCI",
          authorOrder: "第一作者",
          authorOrderOriginal: "第一作者",
          authorOrderModified: false,
          authorOrderChangeNote: "",
          attachmentNote: "",
        },
      ],
      conferences: [
        {
          date: "2025-06-18",
          author: "Zhang, Y.-X., Wu, M.-L., & Kuo, H.-Y.",
          title: "Gamification in Higher Education: Impact on Learning Outcomes",
          conference: "EdMedia + Innovate Learning 2025",
          organizer: "AACE",
          type: "口頭發表",
          database: "",
          authorOrder: "第一作者",
        },
      ],
      researchExperiences: [
        {
          institution: "國科會計畫（吳美玲主持）",
          role: "研究助理",
          nature: "個別型計畫",
          duration: "2024/08 - 2025/07",
        },
      ],
      researchAwards: [
        {
          name: "竹師教育學院學術論文發表獎勵",
          projectNumber: "",
          amountOrItem: "NT$20,000",
          contribution: "第一作者",
        },
      ],
      plannedResearch: [
        {
          title: "生成式AI對大學生批判思考能力影響之實驗研究",
          expectedDate: "2027-06",
          targetVenue: "British Journal of Educational Technology",
          hasTrustedDatabase: "是",
          database: "SSCI",
          advisor: "吳美玲",
        },
      ],
      otherAchievements: "",
      otherReviewDocuments: [],
    },
  },
  {
    id: "a1b2c3d4-0005-4000-a000-000000000005",
    applicant_name: "林雅婷",
    student_id: "110035005",
    department: "教育心理與諮商學系",
    advisor_name: "陳國華",
    gpa: 3.72,
    gpa_scale: 4.3,
    submission_status: "submitted",
    review_status: "自動審核完成",
    submitted_at: "2026-04-18T11:15:00Z",
    created_at: "2026-04-16T14:00:00Z",
    files: [
      { field: "document_transcript", label: null, name: "成績單.pdf", path: "a1b2c3d4-0005/transcript.pdf", type: "application/pdf", size: 200000 },
      { field: "document_advisorRecommendation", label: null, name: "推薦函.pdf", path: "a1b2c3d4-0005/recommendation.pdf", type: "application/pdf", size: 145000 },
      { field: "document_learningPlan", label: null, name: "學習計畫.pdf", path: "a1b2c3d4-0005/plan.pdf", type: "application/pdf", size: 275000 },
      { field: "document_noFullTimeDeclaration", label: null, name: "切結書.pdf", path: "a1b2c3d4-0005/declaration.pdf", type: "application/pdf", size: 96000 },
    ],
    payload: {
      applicantInfo: {
        applicantName: "林雅婷",
        studentId: "110035005",
        department: "教育心理與諮商學系",
        email: "yating.lin@gs.ncku.edu.tw",
        phone: "0956-789-012",
        advisorName: "陳國華",
        admissionAcademicYear: "110",
        studyStatus: "續領",
        applicationType: "培育優秀博士生獎學金",
      },
      eligibility: {
        bachelorRankPercent: "20",
        masterGpa: "3.70",
        gpaScale: "4.3",
        masterPercentScore: "85",
        hasSpecialRecommendation: false,
        noFullTimeJob: true,
        notReceivingOtherScholarship: true,
        eligibilityNotes: "",
      },
      academicPerformance: {
        cumulativeGpa: "3.72",
        cumulativeGpaScale: "4.3",
        classRankPercent: "18",
        completedCredits: "42",
        conductScore: "90",
        transcriptNotes: "",
      },
      journals: [],
      conferences: [
        {
          date: "2025-04-05",
          author: "Lin, Y.-T. & Chen, K.-H.",
          title: "Mindfulness-Based Intervention for Graduate Student Well-being",
          conference: "International Counseling Psychology Conference (ICPC) 2025",
          organizer: "ICPC",
          type: "壁報發表",
          database: "",
          authorOrder: "第一作者",
        },
      ],
      researchExperiences: [
        {
          institution: "衛福部心理健康促進計畫（陳國華協同主持）",
          role: "兼任研究助理",
          nature: "政府委託計畫",
          duration: "2023/01 - 2024/12",
        },
        {
          institution: "國科會計畫（陳國華主持）",
          role: "研究助理",
          nature: "個別型計畫",
          duration: "2025/01 - 2025/12",
        },
      ],
      researchAwards: [],
      plannedResearch: [
        {
          title: "正念認知療法對博士生學術倦怠之介入效果研究",
          expectedDate: "2027-03",
          targetVenue: "Journal of Counseling Psychology",
          hasTrustedDatabase: "是",
          database: "SSCI",
          advisor: "陳國華",
        },
      ],
      otherAchievements: "通過諮商心理師高考",
      otherReviewDocuments: [{ name: "諮商心理師證書" }],
    },
  },
  {
    id: "a1b2c3d4-0006-4000-a000-000000000006",
    applicant_name: "黃柏翰",
    student_id: "113035010",
    department: "數理教育研究所",
    advisor_name: "劉俊廷",
    gpa: 4.05,
    gpa_scale: 4.3,
    submission_status: "submitted",
    review_status: "等待人工審核",
    submitted_at: "2026-04-23T08:30:00Z",
    created_at: "2026-04-21T15:00:00Z",
    files: [
      { field: "document_transcript", label: null, name: "成績單.pdf", path: "a1b2c3d4-0006/transcript.pdf", type: "application/pdf", size: 205000 },
      { field: "document_advisorRecommendation", label: null, name: "推薦函.pdf", path: "a1b2c3d4-0006/recommendation.pdf", type: "application/pdf", size: 155000 },
      { field: "document_learningPlan", label: null, name: "學習計畫.pdf", path: "a1b2c3d4-0006/plan.pdf", type: "application/pdf", size: 300000 },
      { field: "document_noFullTimeDeclaration", label: null, name: "切結書.pdf", path: "a1b2c3d4-0006/declaration.pdf", type: "application/pdf", size: 99000 },
    ],
    payload: {
      applicantInfo: {
        applicantName: "黃柏翰",
        studentId: "113035010",
        department: "數理教育研究所",
        email: "bohan.huang@gs.ncku.edu.tw",
        phone: "0967-890-123",
        advisorName: "劉俊廷",
        admissionAcademicYear: "113",
        studyStatus: "新領",
        applicationType: "培育優秀博士生獎學金",
      },
      eligibility: {
        bachelorRankPercent: "7",
        masterGpa: "4.00",
        gpaScale: "4.3",
        masterPercentScore: "93",
        hasSpecialRecommendation: false,
        noFullTimeJob: true,
        notReceivingOtherScholarship: true,
        eligibilityNotes: "",
      },
      academicPerformance: {
        cumulativeGpa: "4.05",
        cumulativeGpaScale: "4.3",
        classRankPercent: "6",
        completedCredits: "15",
        conductScore: "96",
        transcriptNotes: "",
      },
      journals: [
        {
          doi: "10.1007/s10763-025-10456-8",
          date: "2025-08-15",
          author: "Huang, B.-H., Liu, J.-T., & Yang, W.-C.",
          applicantAuthorName: "Huang, B.-H.",
          doiAuthorNames: ["Huang, B.-H.", "Liu, J.-T.", "Yang, W.-C."],
          issns: ["1571-0068", "1573-1774"],
          title: "Mathematical Modeling Competence in Secondary Education: Cross-Cultural Comparison",
          journal: "International Journal of Science and Mathematics Education, 23(4), 890-915",
          reviewUnit: "Springer",
          journalLevel: "I級期刊",
          indexSource: "依期刊索引對照表自動判別",
          isCorrespondingAuthor: false,
          hasTrustedDatabase: "是",
          database: "SCIE",
          authorOrder: "第一作者",
          authorOrderOriginal: "第一作者",
          authorOrderModified: false,
          authorOrderChangeNote: "",
          attachmentNote: "",
        },
        {
          doi: "10.6278/tjme.202506.002",
          date: "2025-06-01",
          author: "黃柏翰、劉俊廷",
          applicantAuthorName: "黃柏翰",
          doiAuthorNames: ["黃柏翰", "劉俊廷"],
          issns: ["1027-4634"],
          title: "數學建模教學對高中生數學問題解決能力之影響",
          journal: "臺灣數學教育期刊, 12(1), 25-52",
          reviewUnit: "臺灣數學教育學會",
          journalLevel: "非I級期刊",
          indexSource: "未命中索引對照表，請人工選擇",
          isCorrespondingAuthor: false,
          hasTrustedDatabase: "否",
          database: "",
          authorOrder: "第一作者",
          authorOrderOriginal: "第一作者",
          authorOrderModified: false,
          authorOrderChangeNote: "",
          attachmentNote: "",
        },
      ],
      conferences: [
        {
          date: "2025-07-15",
          author: "Huang, B.-H. & Liu, J.-T.",
          title: "GeoGebra-Enhanced Mathematical Reasoning Tasks",
          conference: "13th International Congress on Mathematical Education (ICME-15)",
          organizer: "ICMI",
          type: "口頭發表",
          database: "SCOPUS proceedings",
          authorOrder: "第一作者",
        },
      ],
      researchExperiences: [
        {
          institution: "國科會計畫（劉俊廷主持）",
          role: "研究助理",
          nature: "個別型計畫",
          duration: "2025/02 - 2026/01",
        },
      ],
      researchAwards: [
        {
          name: "全國數學教育研究生論文競賽",
          projectNumber: "",
          amountOrItem: "第一名",
          contribution: "獨立研究",
        },
      ],
      plannedResearch: [
        {
          title: "運算思維融入數學建模教學之設計研究",
          expectedDate: "2027-06",
          targetVenue: "ZDM - Mathematics Education",
          hasTrustedDatabase: "是",
          database: "SSCI",
          advisor: "劉俊廷",
        },
      ],
      otherAchievements: "碩士班期間獲全國數學教育學會年度最佳碩士論文獎",
      otherReviewDocuments: [{ name: "最佳碩士論文獎證明" }, { name: "論文競賽獲獎證明" }],
    },
  },
];
